### ISSUE TITLE
meteor clean-package-cache does not work for me

### ISSUE THREAD

**Issue by derwaldgeist** [klaussner/meteor-cleaner#2]
If I try to run `meteor clean-package-cache` on the command line, `meteor` tells me this is not a valid command. Without the `meteor` prefix, the command works as expected. OS: macOS Sierra.

**Comment by klaussner** [comment]
How did you install the package?

**Comment by derwaldgeist** [comment]
via `npm install -g`

**Comment by klaussner** [comment]
If you want to use it like a Meteor command, you have to install it globally using the npm version that is bundled with Meteor: `meteor npm install -g meteor-cleaner`. 🙂

**Comment by derwaldgeist** [comment]
Ah, I see. Thanks for the info.
