### ISSUE TITLE
Directory not found

### ISSUE THREAD

**Issue by Deadly0** [klaussner/meteor-cleaner#3]
I have `.meteor` folder under `C:\Users\Deadly\AppData\Local\.meteor`

![bug](https://monosnap.com/file/u8ok0Ky8fXE4BKX2iy7KwQWtbUZXi4.png)

**Comment by klaussner** [comment]
Thanks for reporting this, @Deadly0! `meteor-cleaner` isn't supported on Windows for now because Meteor's package cache is structured a little differently than on Linux and macOS. Sorry! :disappointed: I will update the README until I have time to implement Windows support.
